name: Build and Deploy Demo App
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Demo App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Flutter - Check how to do it
      - name: Setup Flutter
        uses: flutter/setup-flutter@v3
        with:
          flutter-version: "3.24.5"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test
